services:
  - type: web
    name: youtube-downloader
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    disk:
      name: temp-storage
      mountPath: /tmp
      sizeGB: 1